// tslint:disable
/**
 * Macrothing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class InitiateUserRequest extends APIModel {
    oid: string;
    emailAddress: string;

    constructor(options?: APIModelOptions) {
        super(InitiateUserRequest.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "oid", type: "string" },
            { name: "emailAddress", type: "string" }
        ];
    }
}




