// tslint:disable
/**
 * Macrothing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class ProblemDetails extends APIModel {
    type: string;
    title: string;
    status: number;
    detail: string;
    instance: string;

    constructor(options?: APIModelOptions) {
        super(ProblemDetails.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "type", type: "string" },
            { name: "title", type: "string" },
            { name: "status", type: "number" },
            { name: "detail", type: "string" },
            { name: "instance", type: "string" }
        ];
    }
}




